# Generated by Django 2.2.1 on 2020-01-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('starttime', models.TimeField(auto_now_add=True)),
                ('username', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_date', models.DateField(auto_now_add=True)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.TimeField(auto_now_add=True)),
                ('taskhead', models.CharField(max_length=50)),
                ('taskdesc', models.TextField(max_length=100)),
                ('closetime', models.TimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Register')),
            ],
        ),
    ]
