# Generated by Django 2.2.1 on 2020-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closetime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='starttime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='username',
            field=models.EmailField(max_length=30),
        ),
    ]
