# Generated by Django 2.2.1 on 2020-01-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20200123_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Register'),
        ),
    ]
